### ISSUE TITLE
[Information Request] PASS2 control file identification.

### ISSUE THREAD

**Issue by lordkelvin441** [kenrector/sigma-cpv-kit#10]
Do we have any identification (file name) for PASS2 control statements used to generate C0F system (loaded off cpcp.tap tape image), or should we rather hunt one on original Siggy-format tapes? Want to compare this vs original system images available on bitsavers.org (need to hunt for FRES too) and hopefully bostrap more recent version of CP-V.

**Comment by kenrector** [comment]
PASS2 commands are found in a job file, $PASS2 in the :SYS account and 
in the BO account for each release, for example,

$PASS2.:C00BO.

Read the -11 for the sysgen procedures.

http://www.bitsavers.org/pdf/sds/sigma/cp-v/707000-11C00_CP-V_C00_Release_Notes_Nov74.pdf

More recent versions are interesting but the Andrews U version on CPCP 
contains many features from E00 and F00, as well as custom features they 
thought were valuable.

I have material for an F00 system but it will not run on the current 
sigma simulator because of a bug.  I plan to include this material in 
the software kit when a fix is available.

Ken

**Comment by lordkelvin441** [comment]
$PASS2 restored from CPCP tape is commented as generating C0P system:
***********************************************************************
*                                                                     *
*        C0P OPERATING SYSTEM FOR ANDREWS UNIVERSITY                  *
*                                                                     *
***********************************************************************
Which seems in line with tape naming ( CPCx => C0x ). Analogously $PASS2CPCO.:SYS contains control for C0O, yet system we start reports as C0F:
...
8:             GJOB 9DIAG,:SYS ERR
6:             ONLINE =   0
6:             BATCH  =   0
6:             FRI, FEB 17,'78 C0F
... 
So it keeps me wondering, -11 also gives good impression how $PASS2.:SYS on #00B0 tape (file name c00b.tap on Bitsavers) would look. Thanks for sharing good news re F00, I won't lie, hoping to stumble on EDMS someday, though just being able to review all SDS9xx Bitsavers tapes (looking like archived in CP-V FSAVE format of all things) is also something to hold to.

JK

**Comment by kenrector** [comment]
Then would you like to close this issue?

**Comment by lordkelvin441** [comment]
I can, yet I wonder if you'll be interested in keeping it open as a channel of discusion on system generation topics. Hopefully more people will find this system interesting

**Comment by kenrector** [comment]
I think it will be better to address individual system topics as separate explicit issues.
